/* Generated By:JJTree: Do not edit this line. ASTattributeClass.java */

package org.objectledge.coral.script.parser;

public class ASTattributeClass extends SimpleNode {
  public ASTattributeClass(int id) {
    super(id);
  }

  public ASTattributeClass(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
