/* Generated By:JJTree: Do not edit this line. ASTalterRelationDeleteForwardStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterRelationDeleteForwardStatement extends ASTalterRelationStatement {
  public ASTalterRelationDeleteForwardStatement(int id) {
    super(id);
  }

  public ASTalterRelationDeleteForwardStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public ASTresource getResource() {
      return resource;
  }
}
