/* Generated By:JJTree: Do not edit this line. ASTalterRelationAddPairs.java */

package org.objectledge.coral.script.parser;

public class ASTalterRelationAddPairs extends SimpleNode {
  public ASTalterRelationAddPairs(int id) {
    super(id);
  }

  public ASTalterRelationAddPairs(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
