/* Generated By:JJTree: Do not edit this line. ASTalterRelationAddPairs.java */

package org.objectledge.coral.script.parser;

public class ASTalterRelationStatement extends SimpleNode {
  public ASTalterRelationStatement(int id) {
    super(id);
  }

  public ASTalterRelationStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public ASTrelation getRelation()
  {
      return relation;
  }
}
