/* Generated By:JJTree: Do not edit this line. ASTalterResourceClassAlterAttributeSetNameStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceClassAlterAttributeSetNameStatement extends SimpleNode {
  public ASTalterResourceClassAlterAttributeSetNameStatement(int id) {
    super(id);
  }

  public ASTalterResourceClassAlterAttributeSetNameStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
