/* Generated By:JJTree: Do not edit this line. ASTattributeDefinitionList.java */

package org.objectledge.coral.script.parser;

public class ASTattributeDefinitionList extends SimpleNode {
  public ASTattributeDefinitionList(int id) {
    super(id);
  }

  public ASTattributeDefinitionList(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
