/* Generated By:JJTree: Do not edit this line. ASTapproximationCondition.java */

package org.objectledge.coral.script.parser;

public class ASTapproximationCondition extends SimpleNode {
  public ASTapproximationCondition(int id) {
    super(id);
  }

  public ASTapproximationCondition(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public String getLHS()
  {
  	return lhs;
  }
  
  public String getRHS()
  {
  	return rhs;
  }
  
  public boolean isRHSLiteral()
  {
  	return literalRHS;
  }
}
