/* Generated By:JJTree: Do not edit this line. ASTalterRoleAddSubrolesStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterRoleAddSubrolesStatement extends ASTalterRoleStatement {
  public ASTalterRoleAddSubrolesStatement(int id) {
    super(id);
  }

  public ASTalterRoleAddSubrolesStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ///////////////////////////////////////////////////////////////////////////////////////////////
  
  public ASTroleList getSubRoles()
  {
      return subRoles;
  }
}
