/* Generated By:JJTree: Do not edit this line. ASTattributeDefinition.java */

package org.objectledge.coral.script.parser;

public class ASTattributeDefinition extends SimpleNode {
  public ASTattributeDefinition(int id) {
    super(id);
  }

  public ASTattributeDefinition(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String getName()
  {
      return name;
  }
  
  public ASTattributeClass getAttributeClass()
  {
      return attributeClass;
  }
  
  public String getDomain()
  {
      return domain;
  }
  
  public ASTattributeFlagList getFlags()
  {
      return attributeFlags;  
  }
}
