/* Generated By:JJTree: Do not edit this line. ASTalterResourceDeleteAttributeStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceDeleteAttributeStatement extends SimpleNode {
  public ASTalterResourceDeleteAttributeStatement(int id) {
    super(id);
  }

  public ASTalterResourceDeleteAttributeStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ///////////////////////////////////////////////////////////////////////////////////////////////
  
  public ASTresource getResource()
  {
      return resource;
  }
  
  public String getAttributeName()
  {
      return attributeName;
  }
}
