/* Generated By:JJTree: Do not edit this line. ASTalterResourceSetNameStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceStatement extends SimpleNode {
  public ASTalterResourceStatement(int id) {
    super(id);
  }

  public ASTalterResourceStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ////////////////////////////////////////////////////////////////////////////////////////////////
  
  public ASTresource getResource()
  {
      return resource;
  }
}
