/* Generated By:JJTree: Do not edit this line. ASTalterResourceClassAlterAttributeSetNameStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceClassAlterAttributeStatement extends ASTalterResourceClassStatement {
  public ASTalterResourceClassAlterAttributeStatement(int id) {
    super(id);
  }

  public ASTalterResourceClassAlterAttributeStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  ///////////////////////////////////////////////////////////////////////////////////////////////
  
  public String getAttributeName()
  {
      return attributeName;
  }
}
