/* Generated By:JJTree: Do not edit this line. ASTalterResourceClassSetJavaClassStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceClassSetJavaClassStatement extends SimpleNode {
  public ASTalterResourceClassSetJavaClassStatement(int id) {
    super(id);
  }

  public ASTalterResourceClassSetJavaClassStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
