/* Generated By:JJTree: Do not edit this line. ASTalterResourceClassAlterAttributeSetDomainStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceClassAlterAttributeSetDbColumnStatement extends ASTalterResourceClassAlterAttributeStatement {
  public ASTalterResourceClassAlterAttributeSetDbColumnStatement(int id) {
    super(id);
  }

  public ASTalterResourceClassAlterAttributeSetDbColumnStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ////////////////////////////////////////////////////////////////////////////////////////////////
  
    public String getDbColumn()
    {
        return dbColumn;
    }
}
