/* Generated By:JJTree: Do not edit this line. ASTalterResourceClassAlterAttributeSetDomainStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceClassAlterAttributeDeleteDbColumnStatement extends ASTalterResourceClassAlterAttributeStatement {
  public ASTalterResourceClassAlterAttributeDeleteDbColumnStatement(int id) {
    super(id);
  }

  public ASTalterResourceClassAlterAttributeDeleteDbColumnStatement(RML p, int id) {
    super(p, id);
  }

    public ASTalterResourceClassAlterAttributeDeleteDbColumnStatement(
        ASTresourceClass resourceClass, String attributeName)
    {
        super(0);
        this.resourceClass = resourceClass;
        this.attributeName = attributeName;
    }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ////////////////////////////////////////////////////////////////////////////////////////////////
  
}
