/* Generated By:JJTree: Do not edit this line. ASTalterRoleSetNameStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterRoleStatement extends SimpleNode {
  public ASTalterRoleStatement(int id) {
    super(id);
  }

  public ASTalterRoleStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ///////////////////////////////////////////////////////////////////////////////////////////////
  
  public ASTrole getRole()
  {
      return role;
  }
}
