/* Generated By:JJTree: Do not edit this line. ASTalterRelationDeleteReverseStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterRelationDeleteReverseStatement extends ASTalterRelationStatement {
  public ASTalterRelationDeleteReverseStatement(int id) {
    super(id);
  }

  public ASTalterRelationDeleteReverseStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public ASTresource getResource() {
      return resource;
  }
  
}
