/* Generated By:JJTree: Do not edit this line. ASTalterResourceClassSetHandlerClassStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceClassSetHandlerClassStatement extends ASTalterResourceClassStatement {
  public ASTalterResourceClassSetHandlerClassStatement(int id) {
    super(id);
  }

  public ASTalterResourceClassSetHandlerClassStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  ///////////////////////////////////////////////////////////////////////////////////////////////
  
  public String getHandlerClass()
  {
      return handlerClass;
  }
}
