/* Generated By:JJTree: Do not edit this line. ASTalterResourceClassAddAttributeStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceClassAddAttributeStatement extends SimpleNode {
  public ASTalterResourceClassAddAttributeStatement(int id) {
    super(id);
  }

  public ASTalterResourceClassAddAttributeStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
