/* Generated By:JJTree: Do not edit this line. ASTattributeFlag.java */

package org.objectledge.coral.script.parser;

public class ASTattributeFlag extends SimpleNode {
  public ASTattributeFlag(int id) {
    super(id);
  }

  public ASTattributeFlag(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  ///////////////////////////////////////////////////////////////////////////////////////////////
  
  public String getValue()
  {
      return value;
  }
}
