/* Generated By:JJTree: Do not edit this line. ASTalterRoleDeleteSubrolesStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterRoleDeleteSubrolesStatement extends SimpleNode {
  public ASTalterRoleDeleteSubrolesStatement(int id) {
    super(id);
  }

  public ASTalterRoleDeleteSubrolesStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
