/* Generated By:JJTree: Do not edit this line. ASTalterResourceClassAlterAttributeSetDomainStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceClassAlterAttributeSetDomainStatement extends ASTalterResourceClassAlterAttributeStatement {
  public ASTalterResourceClassAlterAttributeSetDomainStatement(int id) {
    super(id);
  }

  public ASTalterResourceClassAlterAttributeSetDomainStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ////////////////////////////////////////////////////////////////////////////////////////////////
  
  public String getDomain()
  {
      return domain;
  }
}
