/* Generated By:JJTree: Do not edit this line. ASTalterRelationAddPairsStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterRelationAddPairsStatement extends ASTalterRelationStatement {
  public ASTalterRelationAddPairsStatement(int id) {
    super(id);
  }

  public ASTalterRelationAddPairsStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public ASTresourcePairList getResourcePairs()
  {      
      return pairs;
  }
}
