/* Generated By:JJTree: Do not edit this line. ASTalterResourceSetNameStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceSetNameStatement extends SimpleNode {
  public ASTalterResourceSetNameStatement(int id) {
    super(id);
  }

  public ASTalterResourceSetNameStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
