/* Generated By:JJTree: Do not edit this line. ASTalterAttributeClassSetHandlerClassStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterAttributeClassSetHandlerClassStatement extends SimpleNode {
  public ASTalterAttributeClassSetHandlerClassStatement(int id) {
    super(id);
  }

  public ASTalterAttributeClassSetHandlerClassStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
