/* Generated By:JJTree: Do not edit this line. ASTalterResourceClassAddSuperclassStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceClassAddSuperclassStatement extends SimpleNode {
  public ASTalterResourceClassAddSuperclassStatement(int id) {
    super(id);
  }

  public ASTalterResourceClassAddSuperclassStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
