/* Generated By:JJTree: Do not edit this line. ASTattributeFlagList.java */

package org.objectledge.coral.script.parser;

public class ASTattributeFlagList extends SimpleNode {
  public ASTattributeFlagList(int id) {
    super(id);
  }

  public ASTattributeFlagList(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
