/* Generated By:JJTree: Do not edit this line. ASTalterResourceClassAlterAttributeSetDomainStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceClassAlterAttributeDeleteDomainStatement extends ASTalterResourceClassAlterAttributeStatement {
  public ASTalterResourceClassAlterAttributeDeleteDomainStatement(int id) {
    super(id);
  }

  public ASTalterResourceClassAlterAttributeDeleteDomainStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ////////////////////////////////////////////////////////////////////////////////////////////////
  
}
