/* Generated By:JJTree: Do not edit this line. ASTalterResourceClassDeletePermissionsStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceClassDeletePermissionsStatement extends SimpleNode {
  public ASTalterResourceClassDeletePermissionsStatement(int id) {
    super(id);
  }

  public ASTalterResourceClassDeletePermissionsStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ///////////////////////////////////////////////////////////////////////////////////////////////
  
  public ASTresourceClass getResourceClass()
  {
      return resourceClass;
  }
  
  public ASTpermissionList getPermissions()
  {
      return permissions;
  }  
}
