/* Generated By:JJTree: Do not edit this line. ASTalterAttributeClassSetDbTableStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterAttributeClassSetDbTableStatement extends SimpleNode {
  public ASTalterAttributeClassSetDbTableStatement(int id) {
    super(id);
  }

  public ASTalterAttributeClassSetDbTableStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
