/* Generated By:JJTree: Do not edit this line. ASTalterRelationRemoveReverseStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterRelationRemoveReverseStatement extends SimpleNode {
  public ASTalterRelationRemoveReverseStatement(int id) {
    super(id);
  }

  public ASTalterRelationRemoveReverseStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
