/* Generated By:JJTree: Do not edit this line. ASTalterRelationSetNameStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterRelationSetNameStatement extends ASTalterRelationStatement {
  public ASTalterRelationSetNameStatement(int id) {
    super(id);
  }

  public ASTalterRelationSetNameStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String getNewName() {
      return newName;
  }
}
