/* Generated By:JJTree: Do not edit this line. ASTalterResourceSetAttributeStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceSetAttributeStatement extends SimpleNode {
  public ASTalterResourceSetAttributeStatement(int id) {
    super(id);
  }

  public ASTalterResourceSetAttributeStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ///////////////////////////////////////////////////////////////////////////////////////////////
  
  public ASTresource getResource()
  {
      return resource;
  }
  
  public ASTattribute getAttribute()
  {
      return attribute;
  }
}
