/* Generated By:JJTree: Do not edit this line. ASTalterPermissionSetNameStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterPermissionSetNameStatement extends SimpleNode {
  public ASTalterPermissionSetNameStatement(int id) {
    super(id);
  }

  public ASTalterPermissionSetNameStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  ///////////////////////////////////////////////////////////////////////////////////////////////
  
  public ASTpermission getPermission()
  {
      return permission;
  }
  
  public String getNewName()
  {
      return newName;
  }
}
