/* Generated By:JJTree: Do not edit this line. ASTattributeList.java */

package org.objectledge.coral.script.parser;

public class ASTattributeList extends SimpleNode {
  public ASTattributeList(int id) {
    super(id);
  }

  public ASTattributeList(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
