/* Generated By:JJTree: Do not edit this line. ASTalterRelationRemoveForwardStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterRelationRemoveForwardStatement extends SimpleNode {
  public ASTalterRelationRemoveForwardStatement(int id) {
    super(id);
  }

  public ASTalterRelationRemoveForwardStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
