/* Generated By:JJTree: Do not edit this line. ASTalterResourceClassDeleteSuperclassStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceClassDeleteSuperclassStatement extends ASTalterResourceClassStatement {
  public ASTalterResourceClassDeleteSuperclassStatement(int id) {
    super(id);
  }

  public ASTalterResourceClassDeleteSuperclassStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  ///////////////////////////////////////////////////////////////////////////////////////////////

  public ASTresourceClass getParentClass()
  {
      return superClass;
  }
}
