/* Generated By:JJTree: Do not edit this line. ASTalterAttributeClassSetJavaClassStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterAttributeClassSetJavaClassStatement extends ASTalterAttributeClassStatement {
  public ASTalterAttributeClassSetJavaClassStatement(int id) {
    super(id);
  }

  public ASTalterAttributeClassSetJavaClassStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  ////////////////////////////////////////////////////////////////////////////////////////////////
  
  public String getJavaClass()
  {
      return javaClass;
  }
}
