/* Generated By:JJTree: Do not edit this line. ASTalterResourceClassSetFlagsStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceClassSetFlagsStatement extends SimpleNode {
  public ASTalterResourceClassSetFlagsStatement(int id) {
    super(id);
  }

  public ASTalterResourceClassSetFlagsStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
