/* Generated By:JJTree: Do not edit this line. ASTalterResourceClassDeleteAttributeStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceClassDeleteAttributeStatement extends ASTalterResourceClassAlterAttributeStatement {
  public ASTalterResourceClassDeleteAttributeStatement(int id) {
    super(id);
  }

  public ASTalterResourceClassDeleteAttributeStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
