/* Generated By:JJTree: Do not edit this line. ASTalterRelationDeleteAllStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterRelationDeleteAllStatement extends ASTalterRelationStatement {
  public ASTalterRelationDeleteAllStatement(int id) {
    super(id);
  }

  public ASTalterRelationDeleteAllStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
