/* Generated By:JJTree: Do not edit this line. ASTalterResourceSetOwnerStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterResourceSetOwnerStatement extends ASTalterResourceStatement {
  public ASTalterResourceSetOwnerStatement(int id) {
    super(id);
  }

  public ASTalterResourceSetOwnerStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ///////////////////////////////////////////////////////////////////////////////////////////////
  
  public ASTsubject getOwner()
  {
      return owner;
  }
}
