/* Generated By:JJTree: Do not edit this line. ASTalterRoleSetNameStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterRoleSetNameStatement extends SimpleNode {
  public ASTalterRoleSetNameStatement(int id) {
    super(id);
  }

  public ASTalterRoleSetNameStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
