/* Generated By:JJTree: Do not edit this line. ASTalterRelationDeletePairsStatement.java */

package org.objectledge.coral.script.parser;

public class ASTalterRelationDeletePairsStatement extends ASTalterRelationStatement {
  public ASTalterRelationDeletePairsStatement(int id) {
    super(id);
  }

  public ASTalterRelationDeletePairsStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
    
  public ASTresourcePairList getResourcePairs()
  {      
      return pairs;
  }
  
}
