/* Generated By:JJTree: Do not edit this line. ASTcreateRelationStatement.java */

package org.objectledge.coral.script.parser;

public class ASTcreateRelationStatement extends ASTcreateEntityStatement {
  public ASTcreateRelationStatement(int id) {
    super(id);
  }

  public ASTcreateRelationStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
