/* Generated By:JJTree: Do not edit this line. ASTcreateRoleStatement.java */

package org.objectledge.coral.script.parser;

public class ASTcreateRoleStatement extends SimpleNode {
  public ASTcreateRoleStatement(int id) {
    super(id);
  }

  public ASTcreateRoleStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
