/* Generated By:JJTree: Do not edit this line. ASTcreateAttributeClassStatement.java */

package org.objectledge.coral.script.parser;

public class ASTcreateAttributeClassStatement extends SimpleNode {
  public ASTcreateAttributeClassStatement(int id) {
    super(id);
  }

  public ASTcreateAttributeClassStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
