/* Generated By:JJTree: Do not edit this line. ASTclassAndAliasSpecifier.java */

package org.objectledge.coral.script.parser;

import org.objectledge.coral.schema.ResourceClass;

public class ASTclassAndAliasSpecifier extends SimpleNode {
  public ASTclassAndAliasSpecifier(int id) {
    super(id);
  }

  public ASTclassAndAliasSpecifier(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public ASTresourceClass getResourceClass()
  {
  	  return resourceClass;
  }
  
  public String getAlias()
  {
  	  return alias;
  }
}
