/* Generated By:JJTree: Do not edit this line. ASTcreateResourceClassStatement.java */

package org.objectledge.coral.script.parser;

public class ASTcreateEntityStatement extends SimpleNode {
  public ASTcreateEntityStatement(int id) {
    super(id);
  }

  public ASTcreateEntityStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  ////////////////////////////////////////////////////////////////////////////////////////////////

  public String getName()
  {
      return name;
  }  
}
