/* Generated By:JJTree: Do not edit this line. ASTconditionalExpression.java */

package org.objectledge.coral.script.parser;

public class ASTconditionalExpression extends SimpleNode {
  public ASTconditionalExpression(int id) {
    super(id);
  }

  public ASTconditionalExpression(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
