/* Generated By:JJTree: Do not edit this line. ASTcreateResourceClassStatement.java */

package org.objectledge.coral.script.parser;

public class ASTcreateClassStatement extends ASTcreateEntityStatement {
  public ASTcreateClassStatement(int id) {
    super(id);
  }

  public ASTcreateClassStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  ////////////////////////////////////////////////////////////////////////////////////////////////
  
  public String getJavaClass()
  {
      return javaClass;
  }  

  public String getHandlerClass()
  {
      return javaClass;
  }  
  
  public String getDbTable()
  {
      return dbTable;
  }
}
