/* Generated By:JJTree: Do not edit this line. ASTcreatePermissionStatement.java */

package org.objectledge.coral.script.parser;

public class ASTcreatePermissionStatement extends ASTcreateEntityStatement {
  public ASTcreatePermissionStatement(int id) {
    super(id);
  }

  public ASTcreatePermissionStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
