/* Generated By:JJTree: Do not edit this line. ASTclassAndAliasSpecifierList.java */

package org.objectledge.coral.script.parser;

public class ASTclassAndAliasSpecifierList extends SimpleNode {
  public ASTclassAndAliasSpecifierList(int id) {
    super(id);
  }

  public ASTclassAndAliasSpecifierList(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
