/* Generated By:JJTree: Do not edit this line. ASTcreateResourceStatement.java */

package org.objectledge.coral.script.parser;

public class ASTcreateResourceStatement extends ASTcreateEntityStatement {
  public ASTcreateResourceStatement(int id) {
    super(id);
  }

  public ASTcreateResourceStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ///////////////////////////////////////////////////////////////////////////////////////////////
  
  public ASTresourceClass getResourceClass()
  {
      return resourceClass;
  }
  
  public ASTresource getParent()
  {
      return parentResource;
  }
  
  public ASTattributeList getAttributes()
  {
      return attributeValues;
  }
}
