/* Generated By:JJTree: Do not edit this line. ASTdeleteResourceStatement.java */

package org.objectledge.coral.script.parser;

public class ASTdeleteResourceStatement extends SimpleNode {
  public ASTdeleteResourceStatement(int id) {
    super(id);
  }

  public ASTdeleteResourceStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ///////////////////////////////////////////////////////////////////////////////////////////////
  
  public ASTresource getResource()
  {
      return resource;
  }
  
  public boolean getRecursive()
  {
      return recursive;
  }
}
