/* Generated By:JJTree: Do not edit this line. ASTdeletePermissionStatement.java */

package org.objectledge.coral.script.parser;

public class ASTdeletePermissionStatement extends SimpleNode {
  public ASTdeletePermissionStatement(int id) {
    super(id);
  }

  public ASTdeletePermissionStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ///////////////////////////////////////////////////////////////////////////////////////////////
  
  public ASTpermission getPermission()
  {
      return permission;
  }
}
