/* Generated By:JJTree: Do not edit this line. ASTdeleteAttributeClassStatement.java */

package org.objectledge.coral.script.parser;

public class ASTdeleteAttributeClassStatement extends SimpleNode {
  public ASTdeleteAttributeClassStatement(int id) {
    super(id);
  }

  public ASTdeleteAttributeClassStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ///////////////////////////////////////////////////////////////////////////////////////////////
  
  public ASTattributeClass getAttributeClass()
  {
      return attributeClass;
  }
}
