/* Generated By:JJTree: Do not edit this line. ASTfindSuperrolesStatement.java */

package org.objectledge.coral.script.parser;

public class ASTfindRelatedRolesStatement extends SimpleNode {
  public ASTfindRelatedRolesStatement(int id) {
    super(id);
  }

  public ASTfindRelatedRolesStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ////////////////////////////////////////////////////////////////////////////////////////////////
  
  public ASTrole getRole()
  {
      return role;
  }
  
  public boolean getDirect()
  {
      return direct;
  }
}
