/* Generated By:JJTree: Do not edit this line. ASTfindGrantsForResourceStatement.java */

package org.objectledge.coral.script.parser;

public class ASTfindGrantsForResourceStatement extends SimpleNode {
  public ASTfindGrantsForResourceStatement(int id) {
    super(id);
  }

  public ASTfindGrantsForResourceStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
