/* Generated By:JJTree: Do not edit this line. ASTfindGrantsForRoleStatement.java */

package org.objectledge.coral.script.parser;

public class ASTfindGrantsForRoleStatement extends SimpleNode {
  public ASTfindGrantsForRoleStatement(int id) {
    super(id);
  }

  public ASTfindGrantsForRoleStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
