/* Generated By:JJTree: Do not edit this line. ASTfindRoleStatement.java */

package org.objectledge.coral.script.parser;

public class ASTfindRoleStatement extends SimpleNode {
  public ASTfindRoleStatement(int id) {
    super(id);
  }

  public ASTfindRoleStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
