/* Generated By:JJTree: Do not edit this line. ASTfindSubjectStatement.java */

package org.objectledge.coral.script.parser;

public class ASTfindSubjectStatement extends SimpleNode {
  public ASTfindSubjectStatement(int id) {
    super(id);
  }

  public ASTfindSubjectStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
