/* Generated By:JJTree: Do not edit this line. ASTfindResourceClassStatement.java */

package org.objectledge.coral.script.parser;

public class ASTfindResourceClassStatement extends ASTfindStatement {
  public ASTfindResourceClassStatement(int id) {
    super(id);
  }

  public ASTfindResourceClassStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
