/* Generated By:JJTree: Do not edit this line. ASTfindResourceStatement.java */

package org.objectledge.coral.script.parser;

public class ASTfindResourceStatement extends SimpleNode {
  public ASTfindResourceStatement(int id) {
    super(id);
  }

  public ASTfindResourceStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
