/* Generated By:JJTree: Do not edit this line. ASTfindSuperrolesStatement.java */

package org.objectledge.coral.script.parser;

public class ASTfindSuperrolesStatement extends ASTfindRelatedRolesStatement {
  public ASTfindSuperrolesStatement(int id) {
    super(id);
  }

  public ASTfindSuperrolesStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
