/* Generated By:JJTree: Do not edit this line. ASTfindSubrolesStatement.java */

package org.objectledge.coral.script.parser;

public class ASTfindSubrolesStatement extends SimpleNode {
  public ASTfindSubrolesStatement(int id) {
    super(id);
  }

  public ASTfindSubrolesStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
