/* Generated By:JJTree: Do not edit this line. ASTfindResourceClassStatement.java */

package org.objectledge.coral.script.parser;

public class ASTfindStatement extends SimpleNode {
  public ASTfindStatement(int id) {
    super(id);
  }

  public ASTfindStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  /////////////////////////////////////////////////////////////////////////////////////////////
  
  public long getId()
  {
      return entityId;
  }
  
  public String getName()
  {
      return entityName;
  }
}
