/* Generated By:JJTree: Do not edit this line. ASTfindGrantsForSubjectStatement.java */

package org.objectledge.coral.script.parser;

public class ASTfindGrantsForSubjectStatement extends SimpleNode {
  public ASTfindGrantsForSubjectStatement(int id) {
    super(id);
  }

  public ASTfindGrantsForSubjectStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
