/* Generated By:JJTree: Do not edit this line. ASTfindAttributeClassStatement.java */

package org.objectledge.coral.script.parser;

public class ASTfindAttributeClassStatement extends SimpleNode {
  public ASTfindAttributeClassStatement(int id) {
    super(id);
  }

  public ASTfindAttributeClassStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
