/* Generated By:JJTree: Do not edit this line. ASTfindGrantsForResourceClassStatement.java */

package org.objectledge.coral.script.parser;

public class ASTfindGrantsForResourceClassStatement extends SimpleNode {
  public ASTfindGrantsForResourceClassStatement(int id) {
    super(id);
  }

  public ASTfindGrantsForResourceClassStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ///////////////////////////////////////////////////////////////////////////////////////////////
  
  public ASTresourceClass getResourceClass()
  {
      return resourceClass;
  }
}
