/* Generated By:JJTree: Do not edit this line. ASTfindRelationStatement.java */

package org.objectledge.coral.script.parser;

public class ASTfindRelationStatement extends ASTfindEntityStatement {
  public ASTfindRelationStatement(int id) {
    super(id);
  }

  public ASTfindRelationStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
