/* Generated By:JJTree: Do not edit this line. ASTgrantPermissionStatement.java */

package org.objectledge.coral.script.parser;

public class ASTgrantPermissionStatement extends SimpleNode {
  public ASTgrantPermissionStatement(int id) {
    super(id);
  }

  public ASTgrantPermissionStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ////////////////////////////////////////////////////////////////////////////////////////////////
  
  public ASTrole getRole()
  {
      return role;
  }
  
  public ASTpermission getPermission()
  {
      return permission;
  }
  
  public ASTresource getResource()
  {
      return resource;
  }
  
  public boolean getRecursive()
  {
      return recursive;
  }
}
