/* Generated By:JJTree: Do not edit this line. ASTnotExpression.java */

package org.objectledge.coral.script.parser;

public class ASTnotExpression extends SimpleNode {
  public ASTnotExpression(int id) {
    super(id);
  }

  public ASTnotExpression(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
