/* Generated By:JJTree: Do not edit this line. ASTorderByList.java */

package org.objectledge.coral.script.parser;

public class ASTorderByList extends SimpleNode {
  public ASTorderByList(int id) {
    super(id);
  }

  public ASTorderByList(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
