/* Generated By:JJTree: Do not edit this line. ASTorderBySpecifier.java */

package org.objectledge.coral.script.parser;

public class ASTorderBySpecifier extends SimpleNode {
  public ASTorderBySpecifier(int id) {
    super(id);
  }

  public ASTorderBySpecifier(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public String getAttribute()
  {
      return attributeName;
  }
  
  // true is ascending 
  public boolean getDirection() 
  {
      return dir;
  }
}
