/* Generated By:JJTree: Do not edit this line. ASTpermission.java */

package org.objectledge.coral.script.parser;

public class ASTpermission extends ASTentity {
  public ASTpermission(int id) {
    super(id);
  }

  public ASTpermission(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
