/* Generated By:JJTree: Do not edit this line. ASTpermissionList.java */

package org.objectledge.coral.script.parser;

public class ASTpermissionList extends SimpleNode {
  public ASTpermissionList(int id) {
    super(id);
  }

  public ASTpermissionList(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
