/* Generated By:JJTree: Do not edit this line. ASTresource.java */

package org.objectledge.coral.script.parser;

public class ASTresource extends SimpleNode {
  public ASTresource(int id) {
    super(id);
  }

  public ASTresource(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
