/* Generated By:JJTree: Do not edit this line. ASTrevokeRoleStatement.java */

package org.objectledge.coral.script.parser;

public class ASTrevokeRoleStatement extends SimpleNode {
  public ASTrevokeRoleStatement(int id) {
    super(id);
  }

  public ASTrevokeRoleStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  ////////////////////////////////////////////////////////////////////////////////////////////////
  
  public ASTrole getRole()
  {
      return role;
  }
  
  public ASTsubject getSubject()
  {
      return subject;
  }
}
