/* Generated By:JJTree: Do not edit this line. ASTrelation.java */

package org.objectledge.coral.script.parser;

public class ASTrelation extends ASTentity {
  public ASTrelation(int id) {
    super(id);
  }

  public ASTrelation(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
