/* Generated By:JJTree: Do not edit this line. ASTresourcePair.java */

package org.objectledge.coral.script.parser;

public class ASTresourcePair extends SimpleNode {
  public ASTresourcePair(int id) {
    super(id);
  }

  public ASTresourcePair(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public ASTresource getHead() 
  {
      return pairHead;
  }
  
  public ASTresource getTail()
  {
      return pairTail;
  }
}
