/* Generated By:JJTree: Do not edit this line. ASTresourceClass.java */

package org.objectledge.coral.script.parser;

public class ASTresourceClass extends ASTentity {
  public ASTresourceClass(int id) {
    super(id);
  }

  public ASTresourceClass(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
