/* Generated By:JJTree: Do not edit this line. ASTresourceClassList.java */

package org.objectledge.coral.script.parser;

public class ASTresourceClassList extends SimpleNode {
  public ASTresourceClassList(int id) {
    super(id);
  }

  public ASTresourceClassList(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
