/* Generated By:JJTree: Do not edit this line. ASTresourcePairList.java */

package org.objectledge.coral.script.parser;

public class ASTresourcePairList extends SimpleNode {
  public ASTresourcePairList(int id) {
    super(id);
  }

  public ASTresourcePairList(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
