/* Generated By:JJTree: Do not edit this line. ASTrevokePermissionStatement.java */

package org.objectledge.coral.script.parser;

public class ASTrevokePermissionStatement extends SimpleNode {
  public ASTrevokePermissionStatement(int id) {
    super(id);
  }

  public ASTrevokePermissionStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
