/* Generated By:JJTree: Do not edit this line. ASTrole.java */

package org.objectledge.coral.script.parser;

public class ASTrole extends ASTentity {
  public ASTrole(int id) {
    super(id);
  }

  public ASTrole(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
