/* Generated By:JJTree: Do not edit this line. ASTsingleStatement.java */

package org.objectledge.coral.script.parser;

public class ASTsingleStatement extends SimpleNode {
  public ASTsingleStatement(int id) {
    super(id);
  }

  public ASTsingleStatement(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
