/* Generated By:JJTree: Do not edit this line. ASTselectList.java */

package org.objectledge.coral.script.parser;

public class ASTselectList extends SimpleNode {
  public ASTselectList(int id) {
    super(id);
  }

  public ASTselectList(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
