/* Generated By:JJTree: Do not edit this line. ASTscript.java */

package org.objectledge.coral.script.parser;

public class ASTscript extends SimpleNode {
  public ASTscript(int id) {
    super(id);
  }

  public ASTscript(RML p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RMLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
