/* Generated By:JJTree&JavaCC: Do not edit this line. RMLConstants.java */
package org.objectledge.coral.script.parser;

public interface RMLConstants {

  int EOF = 0;
  int COMMENT = 5;
  int ABSTRACT = 6;
  int ADD = 7;
  int ALL = 8;
  int ALTER = 9;
  int AND = 10;
  int AS = 11;
  int ASC = 12;
  int ATTRIBUTE = 13;
  int ATTRIBUTES = 14;
  int BUILTIN = 15;
  int BY = 16;
  int CLASS = 17;
  int CLASS_UNIQUE = 18;
  int COPY = 19;
  int CREATE = 20;
  int DB = 21;
  int DEFINED = 22;
  int DELETE = 23;
  int DESC = 24;
  int DESCRIPTIVE = 25;
  int DIRECT = 26;
  int DOMAIN = 27;
  int ECHO = 28;
  int FINAL = 29;
  int FIND = 30;
  int FLAGS = 31;
  int FOR = 32;
  int FORWARD = 33;
  int FROM = 34;
  int GRANT = 35;
  int GRANTS = 36;
  int HANDLER = 37;
  int ID = 38;
  int IMPERSONATE = 39;
  int INDEXABLE = 40;
  int JAVA = 41;
  int LIKE = 42;
  int LIKE_NC = 43;
  int NAME = 44;
  int NONE = 45;
  int NOT = 46;
  int OF = 47;
  int ON = 48;
  int OR = 49;
  int OPTION = 50;
  int ORDER = 51;
  int OWNER = 52;
  int PARENT = 53;
  int PERMISSION = 54;
  int PERMISSIONS = 55;
  int READONLY = 56;
  int RECURSIVE = 57;
  int RELATION = 58;
  int RESOURCE = 59;
  int REQUIRED = 60;
  int REVERSE = 61;
  int REVOKE = 62;
  int ROLE = 63;
  int ROLES = 64;
  int SELECT = 65;
  int SELF = 66;
  int SET = 67;
  int SIBLINGS_UNIQUE = 68;
  int SUBJECT = 69;
  int SUBROLES = 70;
  int SUPERCLASS = 71;
  int SUPERCLASSES = 72;
  int SUPERROLES = 73;
  int SYNTHETIC = 74;
  int TABLE = 75;
  int TO = 76;
  int VALUE = 77;
  int VALUES = 78;
  int WITH = 79;
  int WHERE = 80;
  int WHOAMI = 81;
  int DIGIT = 82;
  int LETTER = 83;
  int PATHMETA = 84;
  int STRING = 85;
  int NUMBER = 86;
  int QUOTED_STRING = 87;
  int LPAREN = 88;
  int RPAREN = 89;
  int COMMA = 90;
  int LESS = 91;
  int LESS_EQUALS = 92;
  int GREATER = 93;
  int GREATER_EQUALS = 94;
  int EQUALS = 95;
  int DOUBLE_EQUALS = 96;
  int NOT_EQUALS = 97;
  int SQL_NOT_EQUALS = 98;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "\"ABSTRACT\"",
    "\"ADD\"",
    "\"ALL\"",
    "\"ALTER\"",
    "\"AND\"",
    "\"AS\"",
    "\"ASC\"",
    "\"ATTRIBUTE\"",
    "\"ATTRIBUTES\"",
    "\"BUILTIN\"",
    "\"BY\"",
    "\"CLASS\"",
    "\"CLASS_UNIQUE\"",
    "\"COPY\"",
    "\"CREATE\"",
    "\"DB\"",
    "\"DEFINED\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DESCRIPTIVE\"",
    "\"DIRECT\"",
    "\"DOMAIN\"",
    "\"ECHO\"",
    "\"FINAL\"",
    "\"FIND\"",
    "\"FLAGS\"",
    "\"FOR\"",
    "\"FORWARD\"",
    "\"FROM\"",
    "\"GRANT\"",
    "\"GRANTS\"",
    "\"HANDLER\"",
    "\"ID\"",
    "\"IMPERSONATE\"",
    "\"INDEXABLE\"",
    "\"JAVA\"",
    "\"LIKE\"",
    "\"LIKE_NC\"",
    "\"NAME\"",
    "\"NONE\"",
    "\"NOT\"",
    "\"OF\"",
    "\"ON\"",
    "\"OR\"",
    "\"OPTION\"",
    "\"ORDER\"",
    "\"OWNER\"",
    "\"PARENT\"",
    "\"PERMISSION\"",
    "\"PERMISSIONS\"",
    "\"READONLY\"",
    "\"RECURSIVE\"",
    "\"RELATION\"",
    "\"RESOURCE\"",
    "\"REQUIRED\"",
    "\"REVERSE\"",
    "\"REVOKE\"",
    "\"ROLE\"",
    "\"ROLES\"",
    "\"SELECT\"",
    "\"SELF\"",
    "\"SET\"",
    "\"SIBLINGS_UNIQUE\"",
    "\"SUBJECT\"",
    "\"SUBROLES\"",
    "\"SUPERCLASS\"",
    "\"SUPERCLASSES\"",
    "\"SUPERROLES\"",
    "\"SYNTHETIC\"",
    "\"TABLE\"",
    "\"TO\"",
    "\"VALUE\"",
    "\"VALUES\"",
    "\"WITH\"",
    "\"WHERE\"",
    "\"WHOAMI\"",
    "<DIGIT>",
    "<LETTER>",
    "<PATHMETA>",
    "<STRING>",
    "<NUMBER>",
    "<QUOTED_STRING>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<>\"",
    "\";\"",
  };

}
