/* Generated By:JJTree&JavaCC: Do not edit this line. RMLConstants.java */
package org.objectledge.coral.script.parser;

public interface RMLConstants {

  int EOF = 0;
  int COMMENT = 5;
  int ABSTRACT = 6;
  int ADD = 7;
  int ALL = 8;
  int ALTER = 9;
  int AND = 10;
  int AS = 11;
  int ASC = 12;
  int ATTRIBUTE = 13;
  int ATTRIBUTES = 14;
  int BUILTIN = 15;
  int BY = 16;
  int CLASS = 17;
  int CLASS_UNIQUE = 18;
  int CREATE = 19;
  int DB = 20;
  int DEFINED = 21;
  int DELETE = 22;
  int DESC = 23;
  int DESCRIPTIVE = 24;
  int DIRECT = 25;
  int DOMAIN = 26;
  int ECHO = 27;
  int FINAL = 28;
  int FIND = 29;
  int FLAGS = 30;
  int FOR = 31;
  int FORWARD = 32;
  int FROM = 33;
  int GRANT = 34;
  int GRANTS = 35;
  int HANDLER = 36;
  int ID = 37;
  int IMPERSONATE = 38;
  int INDEXABLE = 39;
  int JAVA = 40;
  int LIKE = 41;
  int LIKE_NC = 42;
  int NAME = 43;
  int NONE = 44;
  int NOT = 45;
  int OF = 46;
  int ON = 47;
  int OR = 48;
  int OPTION = 49;
  int ORDER = 50;
  int OWNER = 51;
  int PARENT = 52;
  int PERMISSION = 53;
  int PERMISSIONS = 54;
  int READONLY = 55;
  int RECURSIVE = 56;
  int RELATION = 57;
  int RESOURCE = 58;
  int REQUIRED = 59;
  int REVERSE = 60;
  int REVOKE = 61;
  int ROLE = 62;
  int ROLES = 63;
  int SELECT = 64;
  int SELF = 65;
  int SET = 66;
  int SIBLINGS_UNIQUE = 67;
  int SUBJECT = 68;
  int SUBROLES = 69;
  int SUPERCLASS = 70;
  int SUPERCLASSES = 71;
  int SUPERROLES = 72;
  int SYNTHETIC = 73;
  int TABLE = 74;
  int TO = 75;
  int VALUE = 76;
  int VALUES = 77;
  int WITH = 78;
  int WHERE = 79;
  int WHOAMI = 80;
  int DIGIT = 81;
  int LETTER = 82;
  int PATHMETA = 83;
  int STRING = 84;
  int NUMBER = 85;
  int QUOTED_STRING = 86;
  int LPAREN = 87;
  int RPAREN = 88;
  int COMMA = 89;
  int LESS = 90;
  int LESS_EQUALS = 91;
  int GREATER = 92;
  int GREATER_EQUALS = 93;
  int EQUALS = 94;
  int DOUBLE_EQUALS = 95;
  int NOT_EQUALS = 96;
  int SQL_NOT_EQUALS = 97;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "\"ABSTRACT\"",
    "\"ADD\"",
    "\"ALL\"",
    "\"ALTER\"",
    "\"AND\"",
    "\"AS\"",
    "\"ASC\"",
    "\"ATTRIBUTE\"",
    "\"ATTRIBUTES\"",
    "\"BUILTIN\"",
    "\"BY\"",
    "\"CLASS\"",
    "\"CLASS_UNIQUE\"",
    "\"CREATE\"",
    "\"DB\"",
    "\"DEFINED\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DESCRIPTIVE\"",
    "\"DIRECT\"",
    "\"DOMAIN\"",
    "\"ECHO\"",
    "\"FINAL\"",
    "\"FIND\"",
    "\"FLAGS\"",
    "\"FOR\"",
    "\"FORWARD\"",
    "\"FROM\"",
    "\"GRANT\"",
    "\"GRANTS\"",
    "\"HANDLER\"",
    "\"ID\"",
    "\"IMPERSONATE\"",
    "\"INDEXABLE\"",
    "\"JAVA\"",
    "\"LIKE\"",
    "\"LIKE_NC\"",
    "\"NAME\"",
    "\"NONE\"",
    "\"NOT\"",
    "\"OF\"",
    "\"ON\"",
    "\"OR\"",
    "\"OPTION\"",
    "\"ORDER\"",
    "\"OWNER\"",
    "\"PARENT\"",
    "\"PERMISSION\"",
    "\"PERMISSIONS\"",
    "\"READONLY\"",
    "\"RECURSIVE\"",
    "\"RELATION\"",
    "\"RESOURCE\"",
    "\"REQUIRED\"",
    "\"REVERSE\"",
    "\"REVOKE\"",
    "\"ROLE\"",
    "\"ROLES\"",
    "\"SELECT\"",
    "\"SELF\"",
    "\"SET\"",
    "\"SIBLINGS_UNIQUE\"",
    "\"SUBJECT\"",
    "\"SUBROLES\"",
    "\"SUPERCLASS\"",
    "\"SUPERCLASSES\"",
    "\"SUPERROLES\"",
    "\"SYNTHETIC\"",
    "\"TABLE\"",
    "\"TO\"",
    "\"VALUE\"",
    "\"VALUES\"",
    "\"WITH\"",
    "\"WHERE\"",
    "\"WHOAMI\"",
    "<DIGIT>",
    "<LETTER>",
    "<PATHMETA>",
    "<STRING>",
    "<NUMBER>",
    "<QUOTED_STRING>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<>\"",
    "\";\"",
  };

}
