/* Generated By:JJTree&JavaCC: Do not edit this line. RMLConstants.java */
package org.objectledge.coral.script.parser;

public interface RMLConstants {

  int EOF = 0;
  int COMMENT = 5;
  int ABSTRACT = 6;
  int ADD = 7;
  int ALTER = 8;
  int AND = 9;
  int AS = 10;
  int ASC = 11;
  int ATTRIBUTE = 12;
  int ATTRIBUTES = 13;
  int BUILTIN = 14;
  int BY = 15;
  int CLASS = 16;
  int CLASS_UNIQUE = 17;
  int CREATE = 18;
  int DB = 19;
  int DEFINED = 20;
  int DELETE = 21;
  int DESC = 22;
  int DESCRIPTIVE = 23;
  int DIRECT = 24;
  int DOMAIN = 25;
  int ECHO = 26;
  int FINAL = 27;
  int FIND = 28;
  int FLAGS = 29;
  int FOR = 30;
  int FROM = 31;
  int GRANT = 32;
  int GRANTS = 33;
  int HANDLER = 34;
  int ID = 35;
  int IMPERSONATE = 36;
  int INDEXABLE = 37;
  int JAVA = 38;
  int LIKE = 39;
  int NAME = 40;
  int NONE = 41;
  int NOT = 42;
  int OF = 43;
  int ON = 44;
  int OR = 45;
  int OPTION = 46;
  int ORDER = 47;
  int OWNER = 48;
  int PARENT = 49;
  int PERMISSION = 50;
  int PERMISSIONS = 51;
  int READONLY = 52;
  int RECURSIVE = 53;
  int RESOURCE = 54;
  int REQUIRED = 55;
  int REVOKE = 56;
  int ROLE = 57;
  int ROLES = 58;
  int SELECT = 59;
  int SELF = 60;
  int SET = 61;
  int SIBLINGS_UNIQUE = 62;
  int SUBJECT = 63;
  int SUBROLES = 64;
  int SUPERCLASS = 65;
  int SUPERCLASSES = 66;
  int SUPERROLES = 67;
  int SYNTHETIC = 68;
  int TABLE = 69;
  int TO = 70;
  int VALUE = 71;
  int VALUES = 72;
  int WITH = 73;
  int WHERE = 74;
  int WHOAMI = 75;
  int DIGIT = 76;
  int LETTER = 77;
  int PATHMETA = 78;
  int STRING = 79;
  int NUMBER = 80;
  int QUOTED_STRING = 81;
  int LPAREN = 82;
  int RPAREN = 83;
  int COMMA = 84;
  int LESS = 85;
  int LESS_EQUALS = 86;
  int GREATER = 87;
  int GREATER_EQUALS = 88;
  int EQUALS = 89;
  int DOUBLE_EQUALS = 90;
  int NOT_EQUALS = 91;
  int SQL_NOT_EQUALS = 92;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "\"ABSTRACT\"",
    "\"ADD\"",
    "\"ALTER\"",
    "\"AND\"",
    "\"AS\"",
    "\"ASC\"",
    "\"ATTRIBUTE\"",
    "\"ATTRIBUTES\"",
    "\"BUILTIN\"",
    "\"BY\"",
    "\"CLASS\"",
    "\"CLASS_UNIQUE\"",
    "\"CREATE\"",
    "\"DB\"",
    "\"DEFINED\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DESCRIPTIVE\"",
    "\"DIRECT\"",
    "\"DOMAIN\"",
    "\"ECHO\"",
    "\"FINAL\"",
    "\"FIND\"",
    "\"FLAGS\"",
    "\"FOR\"",
    "\"FROM\"",
    "\"GRANT\"",
    "\"GRANTS\"",
    "\"HANDLER\"",
    "\"ID\"",
    "\"IMPERSONATE\"",
    "\"INDEXABLE\"",
    "\"JAVA\"",
    "\"LIKE\"",
    "\"NAME\"",
    "\"NONE\"",
    "\"NOT\"",
    "\"OF\"",
    "\"ON\"",
    "\"OR\"",
    "\"OPTION\"",
    "\"ORDER\"",
    "\"OWNER\"",
    "\"PARENT\"",
    "\"PERMISSION\"",
    "\"PERMISSIONS\"",
    "\"READONLY\"",
    "\"RECURSIVE\"",
    "\"RESOURCE\"",
    "\"REQUIRED\"",
    "\"REVOKE\"",
    "\"ROLE\"",
    "\"ROLES\"",
    "\"SELECT\"",
    "\"SELF\"",
    "\"SET\"",
    "\"SIBLINGS_UNIQUE\"",
    "\"SUBJECT\"",
    "\"SUBROLES\"",
    "\"SUPERCLASS\"",
    "\"SUPERCLASSES\"",
    "\"SUPERROLES\"",
    "\"SYNTHETIC\"",
    "\"TABLE\"",
    "\"TO\"",
    "\"VALUE\"",
    "\"VALUES\"",
    "\"WITH\"",
    "\"WHERE\"",
    "\"WHOAMI\"",
    "<DIGIT>",
    "<LETTER>",
    "<PATHMETA>",
    "<STRING>",
    "<NUMBER>",
    "<QUOTED_STRING>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<>\"",
    "\";\"",
  };

}
