/* Generated By:JJTree: Do not edit this line. ./RMLTreeConstants.java */

package org.objectledge.coral.script.parser;

public interface RMLTreeConstants
{
  public int JJTVOID = 0;
  public int JJTATTRIBUTECLASS = 1;
  public int JJTRESOURCECLASS = 2;
  public int JJTSUBJECT = 3;
  public int JJTROLE = 4;
  public int JJTPERMISSION = 5;
  public int JJTRESOURCE = 6;
  public int JJTRELATION = 7;
  public int JJTRESOURCECLASSFLAG = 8;
  public int JJTATTRIBUTEFLAG = 9;
  public int JJTATTRIBUTEDEFINITION = 10;
  public int JJTATTRIBUTE = 11;
  public int JJTRESOURCEPAIR = 12;
  public int JJTRESOURCECLASSLIST = 13;
  public int JJTROLELIST = 14;
  public int JJTPERMISSIONLIST = 15;
  public int JJTRESOURCEPAIRLIST = 16;
  public int JJTATTRIBUTEFLAGLIST = 17;
  public int JJTRESOURCECLASSFLAGLIST = 18;
  public int JJTATTRIBUTEDEFINITIONLIST = 19;
  public int JJTATTRIBUTELIST = 20;
  public int JJTSCRIPT = 21;
  public int JJTSINGLESTATEMENT = 22;
  public int JJTWHOAMISTATEMENT = 23;
  public int JJTCREATEATTRIBUTECLASSSTATEMENT = 24;
  public int JJTFINDATTRIBUTECLASSSTATEMENT = 25;
  public int JJTDELETEATTRIBUTECLASSSTATEMENT = 26;
  public int JJTALTERATTRIBUTECLASSSETNAMESTATEMENT = 27;
  public int JJTALTERATTRIBUTECLASSSETJAVACLASSSTATEMENT = 28;
  public int JJTALTERATTRIBUTECLASSSETHANDLERCLASSSTATEMENT = 29;
  public int JJTALTERATTRIBUTECLASSSETDBTABLESTATEMENT = 30;
  public int JJTCREATERESOURCECLASSSTATEMENT = 31;
  public int JJTFINDRESOURCECLASSSTATEMENT = 32;
  public int JJTDELETERESOURCECLASSSTATEMENT = 33;
  public int JJTALTERRESOURCECLASSSETNAMESTATEMENT = 34;
  public int JJTALTERRESOURCECLASSSETJAVACLASSSTATEMENT = 35;
  public int JJTALTERRESOURCECLASSSETHANDLERCLASSSTATEMENT = 36;
  public int JJTALTERRESOURCECLASSSETDBTABLESTATEMENT = 37;
  public int JJTALTERRESOURCECLASSSETFLAGSSTATEMENT = 38;
  public int JJTALTERRESOURCECLASSALTERATTRIBUTESETNAMESTATEMENT = 39;
  public int JJTALTERRESOURCECLASSALTERATTRIBUTESETFLAGSSTATEMENT = 40;
  public int JJTALTERRESOURCECLASSALTERATTRIBUTESETDOMAINSTATEMENT = 41;
  public int JJTALTERRESOURCECLASSADDATTRIBUTESTATEMENT = 42;
  public int JJTALTERRESOURCECLASSDELETEATTRIBUTESTATEMENT = 43;
  public int JJTALTERRESOURCECLASSADDSUPERCLASSSTATEMENT = 44;
  public int JJTALTERRESOURCECLASSDELETESUPERCLASSSTATEMENT = 45;
  public int JJTCREATEPERMISSIONSTATEMENT = 46;
  public int JJTFINDPERMISSIONSTATEMENT = 47;
  public int JJTDELETEPERMISSIONSTATEMENT = 48;
  public int JJTALTERPERMISSIONSETNAMESTATEMENT = 49;
  public int JJTCREATEROLESTATEMENT = 50;
  public int JJTFINDROLESTATEMENT = 51;
  public int JJTDELETEROLESTATEMENT = 52;
  public int JJTALTERROLESETNAMESTATEMENT = 53;
  public int JJTALTERROLEADDSUBROLESSTATEMENT = 54;
  public int JJTALTERROLEDELETESUBROLESSTATEMENT = 55;
  public int JJTFINDSUBROLESSTATEMENT = 56;
  public int JJTFINDSUPERROLESSTATEMENT = 57;
  public int JJTCREATESUBJECTSTATEMENT = 58;
  public int JJTFINDSUBJECTSTATEMENT = 59;
  public int JJTDELETESUBJECTSTATEMENT = 60;
  public int JJTALTERSUBJECTSETNAMESTATEMENT = 61;
  public int JJTCONDITIONALEXPRESSION = 62;
  public int JJTOREXPRESSION = 63;
  public int JJTANDEXPRESSION = 64;
  public int JJTNOTEXPRESSION = 65;
  public int JJTEQUALITYCONDITION = 66;
  public int JJTCOMPARISONCONDITION = 67;
  public int JJTAPPROXIMATIONCONDITION = 68;
  public int JJTDEFINEDCONDITION = 69;
  public int JJTCLASSANDALIASSPECIFIER = 70;
  public int JJTCLASSANDALIASSPECIFIERLIST = 71;
  public int JJTORDERBYSPECIFIER = 72;
  public int JJTORDERBYLIST = 73;
  public int JJTSELECTSPECIFIER = 74;
  public int JJTSELECTLIST = 75;
  public int JJTCREATERESOURCESTATEMENT = 76;
  public int JJTFINDRESOURCESTATEMENT = 77;
  public int JJTCOPYRESOURCESTATEMENT = 78;
  public int JJTDELETERESOURCESTATEMENT = 79;
  public int JJTALTERRESOURCESETNAMESTATEMENT = 80;
  public int JJTALTERRESOURCESETPARENTSTATEMENT = 81;
  public int JJTALTERRESOURCESETOWNERSTATEMENT = 82;
  public int JJTALTERRESOURCESETATTRIBUTESTATEMENT = 83;
  public int JJTALTERRESOURCEDELETEATTRIBUTESTATEMENT = 84;
  public int JJTALTERRESOURCECLASSADDPERMISSIONSSTATEMENT = 85;
  public int JJTALTERRESOURCECLASSDELETEPERMISSIONSSTATEMENT = 86;
  public int JJTFINDGRANTSFORRESOURCECLASSSTATEMENT = 87;
  public int JJTGRANTROLESTATEMENT = 88;
  public int JJTREVOKEROLESTATEMENT = 89;
  public int JJTFINDROLESSTATEMENT = 90;
  public int JJTFINDGRANTSFORSUBJECTSTATEMENT = 91;
  public int JJTFINDGRANTSFORROLESTATEMENT = 92;
  public int JJTGRANTPERMISSIONSTATEMENT = 93;
  public int JJTREVOKEPERMISSIONSTATEMENT = 94;
  public int JJTFINDGRANTSFORRESOURCESTATEMENT = 95;
  public int JJTCREATERELATIONSTATEMENT = 96;
  public int JJTFINDRELATIONSTATEMENT = 97;
  public int JJTALTERRELATIONSETNAMESTATEMENT = 98;
  public int JJTALTERRELATIONADDPAIRSSTATEMENT = 99;
  public int JJTALTERRELATIONDELETEPAIRSSTATEMENT = 100;
  public int JJTALTERRELATIONDELETEFORWARDSTATEMENT = 101;
  public int JJTALTERRELATIONDELETEREVERSESTATEMENT = 102;
  public int JJTALTERRELATIONDELETEALLSTATEMENT = 103;
  public int JJTDELETERELATIONSTATEMENT = 104;
  public int JJTIMPERSONATESTATEMENT = 105;
  public int JJTECHOSTATEMENT = 106;


  public String[] jjtNodeName = {
    "void",
    "attributeClass",
    "resourceClass",
    "subject",
    "role",
    "permission",
    "resource",
    "relation",
    "resourceClassFlag",
    "attributeFlag",
    "attributeDefinition",
    "attribute",
    "resourcePair",
    "resourceClassList",
    "roleList",
    "permissionList",
    "resourcePairList",
    "attributeFlagList",
    "resourceClassFlagList",
    "attributeDefinitionList",
    "attributeList",
    "script",
    "singleStatement",
    "whoamiStatement",
    "createAttributeClassStatement",
    "findAttributeClassStatement",
    "deleteAttributeClassStatement",
    "alterAttributeClassSetNameStatement",
    "alterAttributeClassSetJavaClassStatement",
    "alterAttributeClassSetHandlerClassStatement",
    "alterAttributeClassSetDbTableStatement",
    "createResourceClassStatement",
    "findResourceClassStatement",
    "deleteResourceClassStatement",
    "alterResourceClassSetNameStatement",
    "alterResourceClassSetJavaClassStatement",
    "alterResourceClassSetHandlerClassStatement",
    "alterResourceClassSetDbTableStatement",
    "alterResourceClassSetFlagsStatement",
    "alterResourceClassAlterAttributeSetNameStatement",
    "alterResourceClassAlterAttributeSetFlagsStatement",
    "alterResourceClassAlterAttributeSetDomainStatement",
    "alterResourceClassAddAttributeStatement",
    "alterResourceClassDeleteAttributeStatement",
    "alterResourceClassAddSuperclassStatement",
    "alterResourceClassDeleteSuperclassStatement",
    "createPermissionStatement",
    "findPermissionStatement",
    "deletePermissionStatement",
    "alterPermissionSetNameStatement",
    "createRoleStatement",
    "findRoleStatement",
    "deleteRoleStatement",
    "alterRoleSetNameStatement",
    "alterRoleAddSubrolesStatement",
    "alterRoleDeleteSubrolesStatement",
    "findSubrolesStatement",
    "findSuperrolesStatement",
    "createSubjectStatement",
    "findSubjectStatement",
    "deleteSubjectStatement",
    "alterSubjectSetNameStatement",
    "conditionalExpression",
    "orExpression",
    "andExpression",
    "notExpression",
    "equalityCondition",
    "comparisonCondition",
    "approximationCondition",
    "definedCondition",
    "classAndAliasSpecifier",
    "classAndAliasSpecifierList",
    "orderBySpecifier",
    "orderByList",
    "selectSpecifier",
    "selectList",
    "createResourceStatement",
    "findResourceStatement",
    "copyResourceStatement",
    "deleteResourceStatement",
    "alterResourceSetNameStatement",
    "alterResourceSetParentStatement",
    "alterResourceSetOwnerStatement",
    "alterResourceSetAttributeStatement",
    "alterResourceDeleteAttributeStatement",
    "alterResourceClassAddPermissionsStatement",
    "alterResourceClassDeletePermissionsStatement",
    "findGrantsForResourceClassStatement",
    "grantRoleStatement",
    "revokeRoleStatement",
    "findRolesStatement",
    "findGrantsForSubjectStatement",
    "findGrantsForRoleStatement",
    "grantPermissionStatement",
    "revokePermissionStatement",
    "findGrantsForResourceStatement",
    "createRelationStatement",
    "findRelationStatement",
    "alterRelationSetNameStatement",
    "alterRelationAddPairsStatement",
    "alterRelationDeletePairsStatement",
    "alterRelationDeleteForwardStatement",
    "alterRelationDeleteReverseStatement",
    "alterRelationDeleteAllStatement",
    "deleteRelationStatement",
    "impersonateStatement",
    "echoStatement",
  };
}
