/* Generated By:JJTree&JavaCC: Do not edit this line. RMLTokenManager.java */
package org.objectledge.coral.script.parser;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.ArrayList;

public class RMLTokenManager implements RMLConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0xffffffffffffffc0L) != 0L || (active1 & 0x200007ffL) != 0L)
         {
            jjmatchedKind = 78;
            return 6;
         }
         return -1;
      case 1:
         if ((active0 & 0x5c0400088c00L) != 0L || (active1 & 0x20L) != 0L)
            return 6;
         if ((active0 & 0xffffa3fbfff773c0L) != 0L || (active1 & 0x200007dfL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 78;
               jjmatchedPos = 1;
            }
            return 6;
         }
         return -1;
      case 2:
         if ((active0 & 0x1000020020000a80L) != 0L)
            return 6;
         if ((active0 & 0xefffe1fbdff77140L) != 0L || (active1 & 0x200007dfL) != 0L)
         {
            jjmatchedKind = 78;
            jjmatchedPos = 2;
            return 6;
         }
         return -1;
      case 3:
         if ((active0 & 0xb0001e04ac00000L) != 0L || (active1 & 0x100L) != 0L)
            return 6;
         if ((active0 & 0xe4ffe01b95377140L) != 0L || (active1 & 0x200006dfL) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 78;
               jjmatchedPos = 3;
            }
            return 6;
         }
         return -1;
      case 4:
         if ((active0 & 0x200c00194030100L) != 0L || (active1 & 0x2d0L) != 0L)
            return 6;
         if ((active0 & 0xe4ff201a01b47040L) != 0L || (active1 & 0x2000040fL) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 78;
               jjmatchedPos = 4;
            }
            return 6;
         }
         return -1;
      case 5:
         if ((active0 & 0x481200101240000L) != 0L || (active1 & 0x480L) != 0L)
            return 6;
         if ((active0 & 0xe07e001a00927040L) != 0L || (active1 & 0x2000000fL) != 0L)
         {
            jjmatchedKind = 78;
            jjmatchedPos = 5;
            return 6;
         }
         return -1;
      case 6:
         if ((active0 & 0xa07e001800823040L) != 0L || (active1 & 0xfL) != 0L)
         {
            jjmatchedKind = 78;
            jjmatchedPos = 6;
            return 6;
         }
         if ((active0 & 0x4000000200104000L) != 0L)
            return 6;
         return -1;
      case 7:
         if ((active0 & 0x2016001800823000L) != 0L || (active1 & 0xfL) != 0L)
         {
            jjmatchedKind = 78;
            jjmatchedPos = 7;
            return 6;
         }
         if ((active0 & 0x8068000000000040L) != 0L)
            return 6;
         return -1;
      case 8:
         if ((active0 & 0x2006000800820000L) != 0L || (active1 & 0x7L) != 0L)
         {
            if (jjmatchedPos != 8)
            {
               jjmatchedKind = 78;
               jjmatchedPos = 8;
            }
            return 6;
         }
         if ((active0 & 0x10001000003000L) != 0L || (active1 & 0x8L) != 0L)
            return 6;
         return -1;
      case 9:
         if ((active0 & 0x2000000800820000L) != 0L)
         {
            if (jjmatchedPos != 9)
            {
               jjmatchedKind = 78;
               jjmatchedPos = 9;
            }
            return 6;
         }
         if ((active0 & 0x6000000002000L) != 0L || (active1 & 0x7L) != 0L)
            return 6;
         return -1;
      case 10:
         if ((active0 & 0x4000800800000L) != 0L)
            return 6;
         if ((active0 & 0x2000000000020000L) != 0L || (active1 & 0x2L) != 0L)
         {
            jjmatchedKind = 78;
            jjmatchedPos = 10;
            return 6;
         }
         return -1;
      case 11:
         if ((active0 & 0x2000000000000000L) != 0L)
         {
            jjmatchedKind = 78;
            jjmatchedPos = 11;
            return 6;
         }
         if ((active0 & 0x20000L) != 0L || (active1 & 0x2L) != 0L)
            return 6;
         return -1;
      case 12:
         if ((active0 & 0x2000000000000000L) != 0L)
         {
            jjmatchedKind = 78;
            jjmatchedPos = 12;
            return 6;
         }
         return -1;
      case 13:
         if ((active0 & 0x2000000000000000L) != 0L)
         {
            jjmatchedKind = 78;
            jjmatchedPos = 13;
            return 6;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000000L);
      case 40:
         return jjStopAtPos(0, 81);
      case 41:
         return jjStopAtPos(0, 82);
      case 44:
         return jjStopAtPos(0, 83);
      case 59:
         return jjStopAtPos(0, 92);
      case 60:
         jjmatchedKind = 84;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8200000L);
      case 61:
         jjmatchedKind = 88;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000000L);
      case 62:
         jjmatchedKind = 86;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800000L);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x3fc0L, 0x0L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0xc000L, 0x0L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x70000L, 0x0L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x1f80000L, 0x20000000L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x2000000L, 0x0L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x7c000000L, 0x0L);
      case 71:
         return jjMoveStringLiteralDfa1_0(0x180000000L, 0x0L);
      case 72:
         return jjMoveStringLiteralDfa1_0(0x200000000L, 0x0L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x1c00000000L, 0x0L);
      case 74:
         return jjMoveStringLiteralDfa1_0(0x2000000000L, 0x0L);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x4000000000L, 0x0L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x38000000000L, 0x0L);
      case 79:
         return jjMoveStringLiteralDfa1_0(0xfc0000000000L, 0x0L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x7000000000000L, 0x0L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x3f8000000000000L, 0x0L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0xfc00000000000000L, 0xfL);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x30L);
      case 86:
         return jjMoveStringLiteralDfa1_0(0x0L, 0xc0L);
      case 87:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x700L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private final int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 61:
         if ((active1 & 0x200000L) != 0L)
            return jjStopAtPos(1, 85);
         else if ((active1 & 0x800000L) != 0L)
            return jjStopAtPos(1, 87);
         else if ((active1 & 0x2000000L) != 0L)
            return jjStopAtPos(1, 89);
         else if ((active1 & 0x4000000L) != 0L)
            return jjStopAtPos(1, 90);
         break;
      case 62:
         if ((active1 & 0x8000000L) != 0L)
            return jjStopAtPos(1, 91);
         break;
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x100a200000000L, active1, 0xd0L);
      case 66:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(1, 19, 6);
         return jjMoveStringLiteralDfa2_0(active0, 0x40L, active1, 0L);
      case 67:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L, active1, 0L);
      case 68:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(1, 34, 6);
         return jjMoveStringLiteralDfa2_0(active0, 0x80L, active1, 0L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x1cfe000000f00000L, active1, 0L);
      case 70:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 42, 6);
         break;
      case 72:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x600L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000400d000000L, active1, 0x100L);
      case 76:
         return jjMoveStringLiteralDfa2_0(active0, 0x10030100L, active1, 0L);
      case 77:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000L, active1, 0L);
      case 78:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 43, 6);
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000200L, active1, 0L);
      case 79:
         if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(1, 69, 6);
         return jjMoveStringLiteralDfa2_0(active0, 0x300030020000000L, active1, 0x20000000L);
      case 80:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000000L, active1, 0L);
      case 82:
         if ((active0 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 44;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x4001c0040000L, active1, 0L);
      case 83:
         if ((active0 & 0x400L) != 0L)
         {
            jjmatchedKind = 10;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x800L, active1, 0L);
      case 84:
         return jjMoveStringLiteralDfa2_0(active0, 0x3000L, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0xc000000000004000L, active1, 0x7L);
      case 87:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000000L, active1, 0L);
      case 89:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(1, 15, 6);
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x8L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private final int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000190030000L, active1, 0L);
      case 66:
         return jjMoveStringLiteralDfa3_0(active0, 0xe000000000000000L, active1, 0x10L);
      case 67:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(2, 11, 6);
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000000000L, active1, 0L);
      case 68:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(2, 7, 6);
         else if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(2, 9, 6);
         return jjMoveStringLiteralDfa3_0(active0, 0x401000000000L, active1, 0L);
      case 69:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000L, active1, 0x200L);
      case 70:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000L, active1, 0L);
      case 72:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L, active1, 0L);
      case 73:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L, active1, 0L);
      case 75:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000L, active1, 0L);
      case 76:
         return jjMoveStringLiteralDfa3_0(active0, 0xf00000000200000L, active1, 0xc0L);
      case 77:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000000L, active1, 0x20000000L);
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0x81020c000000L, active1, 0x8L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L, active1, 0x400L);
      case 80:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000L, active1, 0x7L);
      case 81:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000000L, active1, 0L);
      case 82:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(2, 29, 6);
         return jjMoveStringLiteralDfa3_0(active0, 0x7000001000000L, active1, 0L);
      case 83:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000c00040L, active1, 0L);
      case 84:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 41, 6);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 60, 6);
         return jjMoveStringLiteralDfa3_0(active0, 0x200000003100L, active1, 0x100L);
      case 86:
         return jjMoveStringLiteralDfa3_0(active0, 0x80002000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private final int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 37, 6);
         return jjMoveStringLiteralDfa4_0(active0, 0x4040000L, active1, 0x20000400L);
      case 67:
         if ((active0 & 0x400000L) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x800000L, active1, 0L);
      case 68:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(3, 27, 6);
         return jjMoveStringLiteralDfa4_0(active0, 0x8000200000000L, active1, 0L);
      case 69:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 38, 6);
         else if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 39, 6);
         else if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 40, 6);
         else if ((active0 & 0x100000000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x601c01801200100L, active1, 0x7L);
      case 70:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 59, 6);
         break;
      case 71:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000L, active1, 0L);
      case 72:
         if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 72, 6);
         break;
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000100000L, active1, 0L);
      case 74:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000000000L, active1, 0L);
      case 76:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000004000L, active1, 0x10L);
      case 77:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 30, 6);
         return jjMoveStringLiteralDfa4_0(active0, 0x6000000000000L, active1, 0L);
      case 78:
         return jjMoveStringLiteralDfa4_0(active0, 0x180000000L, active1, 0L);
      case 79:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(3, 25, 6);
         return jjMoveStringLiteralDfa4_0(active0, 0xa0000000000000L, active1, 0L);
      case 82:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000003000L, active1, 0x200L);
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x30000L, active1, 0L);
      case 84:
         return jjMoveStringLiteralDfa4_0(active0, 0x40L, active1, 0x8L);
      case 85:
         return jjMoveStringLiteralDfa4_0(active0, 0x50000000000000L, active1, 0xc0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
private final int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000001000000L, active1, 0L);
      case 69:
         if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(4, 68, 6);
         else if ((active1 & 0x40L) != 0L)
         {
            jjmatchedKind = 70;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(4, 73, 6);
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000000000L, active1, 0x80L);
      case 72:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x8L);
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x2046000000003000L, active1, 0x20000000L);
      case 75:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000000000L, active1, 0L);
      case 76:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(4, 26, 6);
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000L, active1, 0L);
      case 77:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x400L);
      case 78:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000100000L, active1, 0L);
      case 79:
         return jjMoveStringLiteralDfa5_0(active0, 0x8008200000000000L, active1, 0L);
      case 82:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(4, 8, 6);
         else if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 46, 6);
         else if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 47, 6);
         return jjMoveStringLiteralDfa5_0(active0, 0x10000800800040L, active1, 0x7L);
      case 83:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(4, 28, 6);
         else if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 57, 6);
         return jjMoveStringLiteralDfa5_0(active0, 0x20000L, active1, 0L);
      case 84:
         if ((active0 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x100244000L, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000000000L, active1, 0L);
      case 88:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
private final int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000040L, active1, 0L);
      case 66:
         return jjMoveStringLiteralDfa6_0(active0, 0x3000L, active1, 0L);
      case 67:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000000000000L, active1, 0x3L);
      case 69:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(5, 18, 6);
         else if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(5, 21, 6);
         else if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 55, 6);
         return jjMoveStringLiteralDfa6_0(active0, 0x200100000L, active1, 0x8L);
      case 73:
         if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(5, 74, 6);
         return jjMoveStringLiteralDfa6_0(active0, 0x804000L, active1, 0L);
      case 76:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000000000L, active1, 0L);
      case 78:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 45, 6);
         else if ((active1 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(5, 78, 6);
         return jjMoveStringLiteralDfa6_0(active0, 0x2008000000000000L, active1, 0L);
      case 82:
         return jjMoveStringLiteralDfa6_0(active0, 0x60000000000000L, active1, 0x4L);
      case 83:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(5, 32, 6);
         else if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(5, 71, 6);
         return jjMoveStringLiteralDfa6_0(active0, 0x16000800000000L, active1, 0L);
      case 84:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(5, 24, 6);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 48, 6);
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 58, 6);
         break;
      case 95:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
private final int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 66:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000L, active1, 0L);
      case 67:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000040L, active1, 0L);
      case 68:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(6, 20, 6);
         break;
      case 69:
         return jjMoveStringLiteralDfa7_0(active0, 0x8040000000000000L, active1, 0L);
      case 71:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000000000000L, active1, 0L);
      case 73:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000000000L, active1, 0L);
      case 76:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000000L, active1, 0x3L);
      case 78:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(6, 14, 6);
         break;
      case 79:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000L, active1, 0x4L);
      case 80:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000L, active1, 0L);
      case 82:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(6, 33, 6);
         break;
      case 83:
         return jjMoveStringLiteralDfa7_0(active0, 0x6000000000000L, active1, 0L);
      case 84:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 62, 6);
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x8L);
      case 85:
         return jjMoveStringLiteralDfa7_0(active0, 0x23000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
private final int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1);
      return 7;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x3L);
      case 68:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 54, 6);
         break;
      case 69:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 53, 6);
         break;
      case 73:
         return jjMoveStringLiteralDfa8_0(active0, 0x6000000000000L, active1, 0x8L);
      case 76:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000000000L, active1, 0x4L);
      case 78:
         return jjMoveStringLiteralDfa8_0(active0, 0x800020000L, active1, 0L);
      case 83:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 63, 6);
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000000000000L, active1, 0L);
      case 84:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(7, 6, 6);
         return jjMoveStringLiteralDfa8_0(active0, 0x803000L, active1, 0L);
      case 86:
         return jjMoveStringLiteralDfa8_0(active0, 0x10000000000000L, active1, 0L);
      case 89:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 51, 6);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1);
}
private final int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1);
      return 8;
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa9_0(active0, 0x800000000L, active1, 0L);
      case 67:
         if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(8, 67, 6);
         break;
      case 69:
         if ((active0 & 0x1000L) != 0L)
         {
            jjmatchedKind = 12;
            jjmatchedPos = 8;
         }
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 36, 6);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 52, 6);
         return jjMoveStringLiteralDfa9_0(active0, 0x2000L, active1, 0x4L);
      case 73:
         return jjMoveStringLiteralDfa9_0(active0, 0x820000L, active1, 0L);
      case 79:
         return jjMoveStringLiteralDfa9_0(active0, 0x6000000000000L, active1, 0L);
      case 83:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x3L);
      case 95:
         return jjMoveStringLiteralDfa9_0(active0, 0x2000000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1);
}
private final int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1);
      return 9;
   }
   switch(curChar)
   {
      case 78:
         if ((active0 & 0x2000000000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 9;
         }
         return jjMoveStringLiteralDfa10_0(active0, 0x4000000000000L, active1, 0L);
      case 81:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000L, active1, 0L);
      case 83:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(9, 13, 6);
         else if ((active1 & 0x1L) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 9;
         }
         else if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(9, 66, 6);
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x2L);
      case 84:
         return jjMoveStringLiteralDfa10_0(active0, 0x800000000L, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa10_0(active0, 0x2000000000000000L, active1, 0L);
      case 86:
         return jjMoveStringLiteralDfa10_0(active0, 0x800000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1);
}
private final int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(8, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, active1);
      return 10;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(10, 23, 6);
         else if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(10, 35, 6);
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x2L);
      case 78:
         return jjMoveStringLiteralDfa11_0(active0, 0x2000000000000000L, active1, 0L);
      case 83:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 50, 6);
         break;
      case 85:
         return jjMoveStringLiteralDfa11_0(active0, 0x20000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0, active1);
}
private final int jjMoveStringLiteralDfa11_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(9, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, active1);
      return 11;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(11, 17, 6);
         break;
      case 73:
         return jjMoveStringLiteralDfa12_0(active0, 0x2000000000000000L, active1, 0L);
      case 83:
         if ((active1 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(11, 65, 6);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, active0, active1);
}
private final int jjMoveStringLiteralDfa12_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(10, old0, old1); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, 0L);
      return 12;
   }
   switch(curChar)
   {
      case 81:
         return jjMoveStringLiteralDfa13_0(active0, 0x2000000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0, 0L);
}
private final int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0, 0L);
      return 13;
   }
   switch(curChar)
   {
      case 85:
         return jjMoveStringLiteralDfa14_0(active0, 0x2000000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0, 0L);
}
private final int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(12, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0, 0L);
      return 14;
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(14, 61, 6);
         break;
      default :
         break;
   }
   return jjStartNfa_0(13, active0, 0L);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 14;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 79)
                        kind = 79;
                     jjCheckNAdd(7);
                  }
                  else if ((0xc40000000000L & l) != 0L)
                  {
                     if (kind > 78)
                        kind = 78;
                     jjCheckNAdd(6);
                  }
                  else if (curChar == 39)
                     jjCheckNAddStates(0, 2);
                  else if (curChar == 35)
                     jjCheckNAddStates(3, 5);
                  break;
               case 1:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(3, 5);
                  break;
               case 2:
                  if ((0x2400L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 3:
                  if (curChar == 10 && kind > 5)
                     kind = 5;
                  break;
               case 4:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 5:
                  if ((0xc40000000000L & l) == 0L)
                     break;
                  if (kind > 78)
                     kind = 78;
                  jjCheckNAdd(6);
                  break;
               case 6:
                  if ((0x3ffc40000000000L & l) == 0L)
                     break;
                  if (kind > 78)
                     kind = 78;
                  jjCheckNAdd(6);
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 79)
                     kind = 79;
                  jjCheckNAdd(7);
                  break;
               case 8:
               case 12:
                  if (curChar == 39)
                     jjCheckNAddStates(0, 2);
                  break;
               case 9:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 10:
                  if (curChar == 39 && kind > 80)
                     kind = 80;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 6:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 78)
                     kind = 78;
                  jjCheckNAdd(6);
                  break;
               case 1:
                  jjAddStates(3, 5);
                  break;
               case 9:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 11:
                  if (curChar == 92)
                     jjAddStates(6, 7);
                  break;
               case 13:
                  if (curChar == 92)
                     jjCheckNAddStates(0, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(3, 5);
                  break;
               case 9:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(0, 2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 14 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   9, 10, 11, 1, 2, 4, 12, 13, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default : 
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, "\101\102\123\124\122\101\103\124", 
"\101\104\104", "\101\114\124\105\122", "\101\116\104", "\101\123", "\101\123\103", 
"\101\124\124\122\111\102\125\124\105", "\101\124\124\122\111\102\125\124\105\123", "\102\125\111\114\124\111\116", 
"\102\131", "\103\114\101\123\123", "\103\114\101\123\123\137\125\116\111\121\125\105", 
"\103\122\105\101\124\105", "\104\102", "\104\105\106\111\116\105\104", "\104\105\114\105\124\105", 
"\104\105\123\103", "\104\105\123\103\122\111\120\124\111\126\105", "\104\111\122\105\103\124", 
"\105\103\110\117", "\106\111\116\101\114", "\106\111\116\104", "\106\114\101\107\123", 
"\106\117\122", "\106\122\117\115", "\107\122\101\116\124", "\107\122\101\116\124\123", 
"\110\101\116\104\114\105\122", "\111\104", "\111\115\120\105\122\123\117\116\101\124\105", 
"\111\116\104\105\130\101\102\114\105", "\112\101\126\101", "\114\111\113\105", "\116\101\115\105", 
"\116\117\116\105", "\116\117\124", "\117\106", "\117\116", "\117\122", 
"\117\120\124\111\117\116", "\117\122\104\105\122", "\117\127\116\105\122", "\120\101\122\105\116\124", 
"\120\105\122\115\111\123\123\111\117\116", "\120\105\122\115\111\123\123\111\117\116\123", 
"\122\105\101\104\117\116\114\131", "\122\105\103\125\122\123\111\126\105", "\122\105\123\117\125\122\103\105", 
"\122\105\121\125\111\122\105\104", "\122\105\126\117\113\105", "\122\117\114\105", "\122\117\114\105\123", 
"\123\105\114\105\103\124", "\123\105\114\106", "\123\105\124", 
"\123\111\102\114\111\116\107\123\137\125\116\111\121\125\105", "\123\125\102\112\105\103\124", "\123\125\102\122\117\114\105\123", 
"\123\125\120\105\122\103\114\101\123\123", "\123\125\120\105\122\103\114\101\123\123\105\123", 
"\123\125\120\105\122\122\117\114\105\123", "\123\131\116\124\110\105\124\111\103", "\124\101\102\114\105", "\124\117", 
"\126\101\114\125\105", "\126\101\114\125\105\123", "\127\111\124\110", "\127\110\105\122\105", 
"\127\110\117\101\115\111", null, null, null, null, null, null, "\50", "\51", "\54", "\74", "\74\75", 
"\76", "\76\75", "\75", "\75\75", "\41\75", "\74\76", "\73", 
"\104\117\115\101\111\116", };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0xffffffffffffffc1L, 0x3fffc7ffL, 
};
static final long[] jjtoSkip = {
   0x3eL, 0x0L, 
};
private JavaCharStream input_stream;
private final int[] jjrounds = new int[14];
private final int[] jjstateSet = new int[28];
protected char curChar;
public RMLTokenManager(JavaCharStream stream)
{
   if (JavaCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public RMLTokenManager(JavaCharStream stream, int lexState)
{
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(JavaCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 14; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(JavaCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

private final Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public final Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
