/* Generated By:JJTree: Do not edit this line. /home/fil/eclipse/ledge/coral-api/src/main/java/org/objectledge/coral/script/parser/RMLTreeConstants.java */

package org.objectledge.coral.script.parser;

public interface RMLTreeConstants
{
  public int JJTVOID = 0;
  public int JJTATTRIBUTECLASS = 1;
  public int JJTRESOURCECLASS = 2;
  public int JJTSUBJECT = 3;
  public int JJTROLE = 4;
  public int JJTPERMISSION = 5;
  public int JJTRESOURCE = 6;
  public int JJTRESOURCECLASSFLAG = 7;
  public int JJTATTRIBUTEFLAG = 8;
  public int JJTATTRIBUTEDEFINITION = 9;
  public int JJTATTRIBUTE = 10;
  public int JJTRESOURCECLASSLIST = 11;
  public int JJTROLELIST = 12;
  public int JJTPERMISSIONLIST = 13;
  public int JJTATTRIBUTEFLAGLIST = 14;
  public int JJTRESOURCECLASSFLAGLIST = 15;
  public int JJTATTRIBUTEDEFINITIONLIST = 16;
  public int JJTATTRIBUTELIST = 17;
  public int JJTSCRIPT = 18;
  public int JJTSINGLESTATEMENT = 19;
  public int JJTWHOAMISTATEMENT = 20;
  public int JJTCREATEATTRIBUTECLASSSTATEMENT = 21;
  public int JJTFINDATTRIBUTECLASSSTATEMENT = 22;
  public int JJTDELETEATTRIBUTECLASSSTATEMENT = 23;
  public int JJTALTERATTRIBUTECLASSSETNAMESTATEMENT = 24;
  public int JJTALTERATTRIBUTECLASSSETJAVACLASSSTATEMENT = 25;
  public int JJTALTERATTRIBUTECLASSSETHANDLERCLASSSTATEMENT = 26;
  public int JJTALTERATTRIBUTECLASSSETDBTABLESTATEMENT = 27;
  public int JJTCREATERESOURCECLASSSTATEMENT = 28;
  public int JJTFINDRESOURCECLASSSTATEMENT = 29;
  public int JJTDELETERESOURCECLASSSTATEMENT = 30;
  public int JJTALTERRESOURCECLASSSETNAMESTATEMENT = 31;
  public int JJTALTERRESOURCECLASSSETJAVACLASSSTATEMENT = 32;
  public int JJTALTERRESOURCECLASSSETHANDLERCLASSSTATEMENT = 33;
  public int JJTALTERRESOURCECLASSSETFLAGSSTATEMENT = 34;
  public int JJTALTERRESOURCECLASSALTERATTRIBUTESETNAMESTATEMENT = 35;
  public int JJTALTERRESOURCECLASSALTERATTRIBUTESETFLAGSSTATEMENT = 36;
  public int JJTALTERRESOURCECLASSADDATTRIBUTESTATEMENT = 37;
  public int JJTALTERRESOURCECLASSDELETEATTRIBUTESTATEMENT = 38;
  public int JJTALTERRESOURCECLASSADDSUPERCLASSSTATEMENT = 39;
  public int JJTALTERRESOURCECLASSDELETESUPERCLASSSTATEMENT = 40;
  public int JJTCREATEPERMISSIONSTATEMENT = 41;
  public int JJTFINDPERMISSIONSTATEMENT = 42;
  public int JJTDELETEPERMISSIONSTATEMENT = 43;
  public int JJTALTERPERMISSIONSETNAMESTATEMENT = 44;
  public int JJTCREATEROLESTATEMENT = 45;
  public int JJTFINDROLESTATEMENT = 46;
  public int JJTDELETEROLESTATEMENT = 47;
  public int JJTALTERROLESETNAMESTATEMENT = 48;
  public int JJTALTERROLEADDSUBROLESSTATEMENT = 49;
  public int JJTALTERROLEDELETESUBROLESSTATEMENT = 50;
  public int JJTFINDSUBROLESSTATEMENT = 51;
  public int JJTFINDSUPERROLESSTATEMENT = 52;
  public int JJTCREATESUBJECTSTATEMENT = 53;
  public int JJTFINDSUBJECTSTATEMENT = 54;
  public int JJTDELETESUBJECTSTATEMENT = 55;
  public int JJTALTERSUBJECTSETNAMESTATEMENT = 56;
  public int JJTCONDITIONALEXPRESSION = 57;
  public int JJTOREXPRESSION = 58;
  public int JJTANDEXPRESSION = 59;
  public int JJTNOTEXPRESSION = 60;
  public int JJTEQUALITYCONDITION = 61;
  public int JJTCOMPARISONCONDITION = 62;
  public int JJTAPPROXIMATIONCONDITION = 63;
  public int JJTDEFINEDCONDITION = 64;
  public int JJTCLASSANDALIASSPECIFIER = 65;
  public int JJTCLASSANDALIASSPECIFIERLIST = 66;
  public int JJTORDERBYSPECIFIER = 67;
  public int JJTORDERBYLIST = 68;
  public int JJTSELECTSPECIFIER = 69;
  public int JJTSELECTLIST = 70;
  public int JJTCREATERESOURCESTATEMENT = 71;
  public int JJTFINDRESOURCESTATEMENT = 72;
  public int JJTDELETERESOURCESTATEMENT = 73;
  public int JJTALTERRESOURCESETNAMESTATEMENT = 74;
  public int JJTALTERRESOURCESETPARENTSTATEMENT = 75;
  public int JJTALTERRESOURCESETOWNERSTATEMENT = 76;
  public int JJTALTERRESOURCESETATTRIBUTESTATEMENT = 77;
  public int JJTALTERRESOURCEDELETEATTRIBUTESTATEMENT = 78;
  public int JJTALTERRESOURCECLASSADDPERMISSIONSSTATEMENT = 79;
  public int JJTALTERRESOURCECLASSDELETEPERMISSIONSSTATEMENT = 80;
  public int JJTFINDGRANTSFORRESOURCECLASSSTATEMENT = 81;
  public int JJTGRANTROLESTATEMENT = 82;
  public int JJTREVOKEROLESTATEMENT = 83;
  public int JJTFINDROLESSTATEMENT = 84;
  public int JJTFINDGRANTSFORSUBJECTSTATEMENT = 85;
  public int JJTFINDGRANTSFORROLESTATEMENT = 86;
  public int JJTGRANTPERMISSIONSTATEMENT = 87;
  public int JJTREVOKEPERMISSIONSTATEMENT = 88;
  public int JJTFINDGRANTSFORRESOURCESTATEMENT = 89;
  public int JJTIMPERSONATESTATEMENT = 90;
  public int JJTECHOSTATEMENT = 91;


  public String[] jjtNodeName = {
    "void",
    "attributeClass",
    "resourceClass",
    "subject",
    "role",
    "permission",
    "resource",
    "resourceClassFlag",
    "attributeFlag",
    "attributeDefinition",
    "attribute",
    "resourceClassList",
    "roleList",
    "permissionList",
    "attributeFlagList",
    "resourceClassFlagList",
    "attributeDefinitionList",
    "attributeList",
    "script",
    "singleStatement",
    "whoamiStatement",
    "createAttributeClassStatement",
    "findAttributeClassStatement",
    "deleteAttributeClassStatement",
    "alterAttributeClassSetNameStatement",
    "alterAttributeClassSetJavaClassStatement",
    "alterAttributeClassSetHandlerClassStatement",
    "alterAttributeClassSetDbTableStatement",
    "createResourceClassStatement",
    "findResourceClassStatement",
    "deleteResourceClassStatement",
    "alterResourceClassSetNameStatement",
    "alterResourceClassSetJavaClassStatement",
    "alterResourceClassSetHandlerClassStatement",
    "alterResourceClassSetFlagsStatement",
    "alterResourceClassAlterAttributeSetNameStatement",
    "alterResourceClassAlterAttributeSetFlagsStatement",
    "alterResourceClassAddAttributeStatement",
    "alterResourceClassDeleteAttributeStatement",
    "alterResourceClassAddSuperclassStatement",
    "alterResourceClassDeleteSuperclassStatement",
    "createPermissionStatement",
    "findPermissionStatement",
    "deletePermissionStatement",
    "alterPermissionSetNameStatement",
    "createRoleStatement",
    "findRoleStatement",
    "deleteRoleStatement",
    "alterRoleSetNameStatement",
    "alterRoleAddSubrolesStatement",
    "alterRoleDeleteSubrolesStatement",
    "findSubrolesStatement",
    "findSuperrolesStatement",
    "createSubjectStatement",
    "findSubjectStatement",
    "deleteSubjectStatement",
    "alterSubjectSetNameStatement",
    "conditionalExpression",
    "orExpression",
    "andExpression",
    "notExpression",
    "equalityCondition",
    "comparisonCondition",
    "approximationCondition",
    "definedCondition",
    "classAndAliasSpecifier",
    "classAndAliasSpecifierList",
    "orderBySpecifier",
    "orderByList",
    "selectSpecifier",
    "selectList",
    "createResourceStatement",
    "findResourceStatement",
    "deleteResourceStatement",
    "alterResourceSetNameStatement",
    "alterResourceSetParentStatement",
    "alterResourceSetOwnerStatement",
    "alterResourceSetAttributeStatement",
    "alterResourceDeleteAttributeStatement",
    "alterResourceClassAddPermissionsStatement",
    "alterResourceClassDeletePermissionsStatement",
    "findGrantsForResourceClassStatement",
    "grantRoleStatement",
    "revokeRoleStatement",
    "findRolesStatement",
    "findGrantsForSubjectStatement",
    "findGrantsForRoleStatement",
    "grantPermissionStatement",
    "revokePermissionStatement",
    "findGrantsForResourceStatement",
    "impersonateStatement",
    "echoStatement",
  };
}
