/* Generated By:JJTree: Do not edit this line. ASTRelationMapExpression.java */

package org.objectledge.coral.relation.query.parser;

public class ASTRelationMapExpression extends SimpleNode {
  public ASTRelationMapExpression(int id) {
    super(id);
  }

  public ASTRelationMapExpression(RelationQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RelationQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
