/* Generated By:JJTree: Do not edit this line. ASTResourceIdentifierPath.java */

package org.objectledge.coral.relation.query.parser;

public class ASTResourceIdentifierPath extends SimpleNode {

  String identifier;

  public ASTResourceIdentifierPath(int id) {
    super(id);
  }

  public ASTResourceIdentifierPath(RelationQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RelationQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

  public String getIdentifier() {
	return identifier;
  }
}
