/* Generated By:JJTree: Do not edit this line. ASTRelationName.java */

package org.objectledge.coral.relation.query.parser;

public class ASTRelationName extends SimpleNode {

  String relationName;

  public ASTRelationName(int id) {
    super(id);
  }

  public ASTRelationName(RelationQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RelationQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String getRelationName() {
	return relationName;
  }
}
