/* Generated By:JJTree: Do not edit this line. ASTSumExpression.java */

package org.objectledge.coral.relation.query.parser;

public class ASTSumExpression extends SimpleNode {
  public ASTSumExpression(int id) {
    super(id);
  }

  public ASTSumExpression(RelationQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RelationQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
