/* Generated By:JJTree: Do not edit this line. ASTTransitiveRelationMapExpression.java */

package org.objectledge.coral.relation.query.parser;

public class ASTTransitiveRelationMapExpression extends SimpleNode {
  public ASTTransitiveRelationMapExpression(int id) {
    super(id);
  }

  public ASTTransitiveRelationMapExpression(RelationQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RelationQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
