/* Generated By:JJTree&JavaCC: Do not edit this line. RelationQueryParserConstants.java */
package org.objectledge.coral.relation.query.parser;

public interface RelationQueryParserConstants {

  int EOF = 0;
  int SUM = 5;
  int INTERSECT = 6;
  int IDENTIFIER_ID = 7;
  int IDENTIFIER_PATH = 8;
  int IDENTIFIER_NAME = 9;
  int LETTER = 10;
  int NUM = 11;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"+\"",
    "\"*\"",
    "<IDENTIFIER_ID>",
    "<IDENTIFIER_PATH>",
    "<IDENTIFIER_NAME>",
    "<LETTER>",
    "<NUM>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"MAP(\"",
    "\"{\"",
    "\"}\"",
    "\"MAPTRANS(\"",
    "\"!\"",
    "\"\\\'\"",
    "\"RES(\"",
  };

}
