/* Generated By:JJTree: Do not edit this line. /home/fil/eclipse/ledge/coral-api/target/javacc/org/objectledge/coral/relation/query/parser/RelationQueryParserVisitor.java */

package org.objectledge.coral.relation.query.parser;

public interface RelationQueryParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTSumExpression node, Object data);
  public Object visit(ASTIntersectionExpression node, Object data);
  public Object visit(ASTRelationMapExpression node, Object data);
  public Object visit(ASTTransitiveRelationMapExpression node, Object data);
  public Object visit(ASTInvertedRelationExpression node, Object data);
  public Object visit(ASTRelationName node, Object data);
  public Object visit(ASTResourceIdentifierId node, Object data);
  public Object visit(ASTResourceIdentifierPath node, Object data);
}
