/* Generated By:JJTree: Do not edit this line. ./RelationQueryParserTreeConstants.java */

package org.objectledge.coral.relation.query.parser;

public interface RelationQueryParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTSUMEXPRESSION = 2;
  public int JJTINTERSECTIONEXPRESSION = 3;
  public int JJTRELATIONMAPEXPRESSION = 4;
  public int JJTTRANSITIVERELATIONMAPEXPRESSION = 5;
  public int JJTINVERTEDRELATIONEXPRESSION = 6;
  public int JJTRELATIONNAME = 7;
  public int JJTRESOURCEIDENTIFIERID = 8;
  public int JJTRESOURCEIDENTIFIERPATH = 9;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "SumExpression",
    "IntersectionExpression",
    "RelationMapExpression",
    "TransitiveRelationMapExpression",
    "InvertedRelationExpression",
    "RelationName",
    "ResourceIdentifierId",
    "ResourceIdentifierPath",
  };
}
